### ISSUE TITLE
Bokeh app command line argument --color-column cannot handle numeric data

### ISSUE THREAD

**Issue by GenevieveBuckley** [microscopium/microscopium#110]
The bokeh web app command line argument `--color-column` works really well for categorical data, but does **not** work for numeric data.

```
ValueError: expected a value of type str, got -0.437314163 of type float64
```

Full traceback:

```
Traceback (most recent call last):
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/bokeh/server/views/doc_handler.py", line 21, in get
    session = yield self.get_session()
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/bokeh/server/views/session_handler.py", line 43, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/bokeh/server/application_context.py", line 182, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/bokeh/application/application.py", line 169, in initialize_document
    h.modify_document(doc)
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/bokeh/application/handlers/function.py", line 126, in modify_document
    self._func(doc)
  File "microscopium/serve.py", line 296, in makedoc
    embed = embedding(source, glyph_size=10, color_column=color_column)
  File "microscopium/serve.py", line 186, in embedding
    group_filter = GroupFilter(column_name=color_column, group=group)
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/bokeh/models/filters.py", line 74, in __init__
    super(GroupFilter, self).__init__(**kw)
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/bokeh/models/filters.py", line 25, in __init__
    super(Filter, self).__init__(**kw)
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/bokeh/model.py", line 219, in __init__
    super(Model, self).__init__(**kwargs)
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/bokeh/core/has_props.py", line 236, in __init__
    setattr(self, name, value)
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/bokeh/core/has_props.py", line 263, in __setattr__
    super(HasProps, self).__setattr__(name, value)
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 503, in __set__
    self._internal_set(obj, value, setter=setter)
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 724, in _internal_set
    value = self.property.prepare_value(obj, self.name, value)
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/bokeh/core/property/bases.py", line 285, in prepare_value
    raise e
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/bokeh/core/property/bases.py", line 278, in prepare_value
    self.validate(value)
  File "/anaconda3/envs/mic/lib/python3.6/site-packages/bokeh/core/property/bases.py", line 410, in validate
    raise ValueError(msg)
ValueError: expected a value of type str, got -0.437314163 of type float64
```

**Comment by jni** [comment]
Yes, looking at the code, the calls to "unique" and the for-loop really presume categorical data. For float data, and maybe even numeric (int) data, we should do a linear colormap and present a colorbar (maybe with sliders), instead of a legend. I think for the latter category (ints) we should have some threshold on the maximum number of unique values before it goes from legend to colorbar.

**Comment by GenevieveBuckley** [comment]
This is the same error as described in https://github.com/microscopium/microscopium/issues/163
Closing this issue in favour of that one.
