### ISSUE TITLE
Error 500 on demo after install bokeh 2.2.3

### ISSUE THREAD

**Issue by Gpotier** [microscopium/microscopium#173]
After a first install I run the demo using :
`python -m microscopium.serve tests/testdata/images/data.csv -c tests/testdata/images/settings.yaml`

Then I get :
```
ready!
WARNING:bokeh.server.util:Host wildcard '*' will allow connections originating from multiple (or possibly all) hostnames or IPs. Use non-wildcard values to restrict access explicitly
Web app now available at http://localhost:5000
BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead
BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead
BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead
BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead
ERROR:tornado.application:Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/guillaume/.local/lib/python3.9/site-packages/bokeh/server/views/doc_handler.py", line 52, in get
    session = await self.get_session()
  File "/home/guillaume/.local/lib/python3.9/site-packages/bokeh/server/views/session_handler.py", line 120, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/home/guillaume/.local/lib/python3.9/site-packages/bokeh/server/contexts.py", line 218, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/home/guillaume/.local/lib/python3.9/site-packages/bokeh/application/application.py", line 171, in initialize_document
    h.modify_document(doc)
  File "/home/guillaume/.local/lib/python3.9/site-packages/bokeh/application/handlers/function.py", line 132, in modify_document
    self._func(doc)
  File "/home/guillaume/Documents/labexigo/microscopium/microscopium/serve.py", line 360, in makedoc
    controls = [button_save_table(table), button_print_page()]
  File "/home/guillaume/Documents/labexigo/microscopium/microscopium/serve.py", line 269, in button_save_table
    button.callback = CustomJS(args=dict(source=table.source),
  File "/home/guillaume/.local/lib/python3.9/site-packages/bokeh/core/has_props.py", line 285, in __setattr__
    raise AttributeError("unexpected attribute '%s' to %s, %s attributes are %s" %
AttributeError: unexpected attribute 'callback' to Button, similar attributes are js_event_callbacks
ERROR:tornado.access:500 GET / (127.0.0.1) 41.33ms
```

Current installed version of bokeh is 2.2.3

**Comment by rmnasl** [comment]
Reinstall bokeh to 1.0.0 version
