### ISSUE TITLE
 "500 Internal Error"

### ISSUE THREAD

**Issue by Jamwali** [microscopium/microscopium#177]
I'm currently using microscopium for personal use and wanted to deploy it on the internet, but whenever I reload the web, it shows "500 Internal Error". I can't find a way to get around it. If you could help me out it would be greatly appreciated.
I installed the dependencies using **pip install -r requirements.txt**
This is the traceback error i got:
```
Traceback (most recent call last):
  File "C:\Users\Ishaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tornado\web.py", line 1786, in _execute
    result = await result
  File "C:\Users\Ishaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bokeh\server\views\doc_handler.py", line 54, in get
    session = await self.get_session()
  File "C:\Users\Ishaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bokeh\server\views\session_handler.py", line 144, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "C:\Users\Ishaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bokeh\server\contexts.py", line 243, in create_session_if_needed
    self._application.initialize_document(doc)
  File "C:\Users\Ishaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bokeh\application\application.py", line 194, in initialize_document
    h.modify_document(doc)
  File "C:\Users\Ishaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bokeh\application\handlers\function.py", line 143, in modify_document
    self._func(doc)
  File "C:\Users\Ishaan\microscopium\microscopium\serve.py", line 359, in makedoc
    prepare_xy(source, settings)  # get the default embedding columns
  File "C:\Users\Ishaan\microscopium\microscopium\serve.py", line 50, in prepare_xy
    default_embedding = settings['embeddings']['default']
KeyError: 'default'
500 GET / (::1) 4.00ms
```
and this is my .yaml file:
```
embeddings:
  G_Points:
    x: x
    y: y 
  default: G_Points
color-columns:
  categorical:
    - label
    - mapType
  numeric:
    - z
image-column:
  url
tooltip-columns:
  - timeZero
  - frame
  - volume
  - count
  - power 
plots:
  glyph_size: 10
```

**Comment by jni** [comment]
Hmmm, weird — the yaml file looks good! And I can see that the settings > embeddings > default key is in fact right there. 🤔 

Would you be able to give me a tiny sample dataset to go with the yaml so I can experiment? Values can be randomised if you don't want to share your real data.

What I would aim to do is to run the code in a debugger (`python -m pdb -m microscopium.serve settings.yml`) and when it crashes, check what is in the settings dictionary. Maybe that will give a clue about why the default key is missing... (Here is a good tutorial on using a debugger, if you haven't done that before: https://realpython.com/python-debugging-pdb/)

**Comment by jni** [comment]
Ok, so I can't drop into the debugger once the bokeh server has started, so I just added a print statement for settings right above the failing line. On first load it was:

```
{'embeddings': {'G_Points': {'x': 'x', 'y': 'y'}, 'default': 'G_Points'}, 'color-columns': {'categorical': ['label', 'mapType'], 'numeric': ['z']}, 'image-column': 'url', 'tooltip-columns': ['timeZero', 'frame', 'volume', 'count', 'power'], 'plots': {'glyph_size': 10}}
```

And on reload it is:

```
{'embeddings': {'G_Points': {'x': 'x', 'y': 'y'}}, 'color-columns': {'categorical': ['label', 'mapType'], 'numeric': ['z']}, 'image-column': 'url', 'tooltip-columns': ['timeZero', 'frame', 'volume', 'count', 'power'], 'plots': {'glyph_size': 10}}
```

The default is gone! So clearly something is deleting it. And, sure enough, this line deletes the key:

https://github.com/microscopium/microscopium/blob/5b7b783b3216b26c1b91a7c12042a438f2c2e8ae/microscopium/serve.py#L307

By changing it as I've done in #178, it's now fixed! 🥳

**Comment by jni** [comment]
btw, just another bug to watch out for: #179. Evidently we never anticipated that people would have columns called "x" and "y" in their dataframe. 😂 🤦
